services:
  telly-vc-p:
    build: .
    environment:
      API_ID: $API_ID  
      API_HASH: $API_HASH  
      BOT_TOKEN: $BOT_TOKEN
      OWNER_ID: $OWNER_ID
      LOG_CHANNEL: $LOG_CHANNEL
      UPDATES_CHANNEL: $UPDATES_CHANNEL
      DATABASE_URL: $DATABASE_URL
      BOT_USERNAME: $BOT_USERNAME
    resources:
      cpu: 1000m
      memory: 3Gi
